---
language: generic
# Use the new container infrastructure
sudo: required

env:
  - PHP_VERSION: 5.6
  - PHP_VERSION: 7.0
  - PHP_VERSION: 7.1

services:
  - docker

cache:
  directories:
    - $HOME/.composer

install:
  - cd $PHP_VERSION
  # Build image
  - sudo docker build . -t kibatic/symfony:$PHP_VERSION
  # Check installed php version
  - sudo docker run -it kibatic/symfony:$PHP_VERSION php --version | grep "PHP $PHP_VERSION"

script:
  - sudo docker build -f tests/Dockerfile . -t kibatic/symfony-demo:$PHP_VERSION
  - git clone --branch v0.9.8 https://github.com/symfony/symfony-demo symfony; cd symfony
  - sudo docker run --rm -v $(pwd):/var/www -v $HOME/.composer:/root/.composer kibatic/symfony-demo:$PHP_VERSION composer install --no-progress
  - sudo docker run -d -p 8001:80 -v $(pwd):/var/www kibatic/symfony-demo:$PHP_VERSION
  - sleep 10
  - sudo docker run --rm -v $(pwd):/var/www kibatic/symfony-demo:$PHP_VERSION vendor/bin/phpunit
  - curl -s localhost:8001 | grep -q "Welcome to the <strong>Symfony Demo</strong> application"

notifications:
  email: true
